### ISSUE TITLE
AttributeError: 'Demo' object has no attribute 'canon_depth'

### ISSUE THREAD

**Issue by sudoboi** [TencentYoutuResearch/3DFaceReconstruction-LAP#2]
I get the following error when trying to run the model on the sample images provided.

Loading checkpoint from ./demo/checkpoint300.pth
Saving checkpoint to ./demo/checkpoint300_fix2.pth
Processing ./images/001.png
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Rendering video animations
Traceback (most recent call last):
  File "demo.py", line 347, in <module>
    result_code = model.run(pil_im)
  File "demo.py", line 252, in run
    self.render_animation()
  File "demo.py", line 256, in render_animation
    b, h, w = self.canon_depth.shape
AttributeError: 'Demo' object has no attribute 'canon_depth'

It looks like the object of class Demo as defined in demo.py does not have the canon_depth attribute in the current version of the code.

**Comment by JesseZhang92** [comment]
We have fixed this bug.
