### ISSUE TITLE
Excuse me, I want to ask you a question

### ISSUE THREAD

**Issue by huyu-coder** [TencentYoutuResearch/3DFaceReconstruction-LAP#3]
Hello,JesseZhang92 ！Does your project will disclose the code of the model part of the model, how does the two indicators of MAD, SIDE assessment? I am looking forward to your reply.Thanks!

**Comment by JesseZhang92** [comment]
Hi, we will release the training code later. The function of MAD and SIDE can be found at https://github.com/TencentYoutuResearch/3DFaceReconstruction-LAP/blob/master/lap/utils.py
