### ISSUE TITLE
About training in resolution of 256×256

### ISSUE THREAD

**Issue by YunjieYu** [TencentYoutuResearch/3DFaceReconstruction-LAP#7]
Hi! Thank you very much for such a great work!

I have a question about training in the size of 256×256 mentioned in your paper. Based on unsuper3d framework, I find that a single rendering time (i.e., rendering warped_depth) for 256×256 takes ~0.48 s in one NVIDIA Tesla V100 GPU, meaning that it takes ~38 days to train for 30 epoch. So I want to know if you have adopted a special differentiable renderer or parallel rendering method to speed up.

Again thank you for your work, looking forward to your reply :>.

**Comment by JesseZhang92** [comment]
Hi, sorry for the late reply. The training on 256x setting is slow if you turn on the anti_aliasing option. A simple solution is to set 'anti_aliasing = False' in the renderer. In addition, you may try pytorch3D to accelerate the training.
